contents:
  - name: geometry_cjj
    code: geometry_cjj.cpp
  - name: geometry_jiangly
    code: geometry_jly.cpp
  - name: 三维计算几何
    code: 3D_geometry.cpp
  - name: 分数点类
    code: Point_Frac.cpp
  - name: 三角剖分
    code: Triangulation.cpp
