contents:
  - name: dsu_on_tree
    code: dsu_on_tree.cpp
  - name: get_centroid
    code: get_centroid.cpp
  - name: LCA
    code: LCA.cpp
  - name: level_ancestor
    code: level_ancestor.cpp
  - name: rmqLCA
    code: rmqLCA.cpp
  - name: treeHash
    code: treeHash.cpp
  - name: treeMaxPath
    code: treeMaxPath.cpp
  - name: virtualTree
    code: virtualTree.cpp
