contents:
  - name: LCA
    directory: LCA
  - name: 树上启发式合并
    code: dsu_on_tree.cpp
  - name: 树的重心
    code: get_centroid.cpp
  - name: 树上k级祖先
    code: level_ancestor.cpp
  - name: 树哈希
    code: treeHash.cpp
  - name: 虚树
    code: virtualTree.cpp
  - name: treeMaxPath
    code: treeMaxPath.cpp
  - name: 树链求交
    code: PathUnion.cpp
